version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workforce-scheduler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uua8kx0s89vi"
s3_prefix = "workforce-scheduler"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["CreateScheduleFn=050362355799.dkr.ecr.eu-west-1.amazonaws.com/workforce-scheduler-ecr"]
disable_rollback = true
