AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  workforce-scheduler-sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 8
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'content-type'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"

Resources:
  CreateScheduleFn:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      Events:
        CreateSchedule:
          Type: Api 
          Properties:
            Path: /create_schedule
            Method: any

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./Main

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateScheduleAPI:
    Description: "API Gateway endpoint URL for Prod stage for CreateScheduleFn function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_schedule/"
  CreateScheduleFn:
    Description: "Create Schedule Function ARN"
    Value: !GetAtt CreateScheduleFn.Arn
  CreateScheduleFnIamRole:
    Description: "Implicit IAM Role created for Create Schedule function"
    Value: !GetAtt CreateScheduleFnRole.Arn
